#ifndef _H_IO_PORTS_
#define _H_IO_PORTS_

#define IO_PORT_MPIC_COM 0x20
#define IO_PORT_MPIC_DAT 0x21
#define IO_PORT_SPIC_COM 0xa0
#define IO_PORT_SPIC_DAT 0xa1

#define IO_PORT_CHECKPOINT 0x80

#define IO_PORT_COM1_BASE 0x3f8
#define IO_PORT_COM2_BASE 0x2f8
#define IO_PORT_COM3_BASE 0x3e8
#define IO_PORT_COM4_BASE 0x2e8
#define IO_PORT_COM_DAT 0x0
#define IO_PORT_COM_INT_ENABLE 0x1
#define IO_PORT_COM_INT_ID 0x2
#define IO_PORT_COM_LINE_CONTROL 0x3
#define IO_PORT_COM_MODEM_CONTROL 0x4
#define IO_PORT_COM_LINE_STATUS 0x5
#define IO_PORT_COM_MODEM_STATUS 0x6
#define IO_PORT_COM_SCRATCH 0x7

#endif
